version: '3.8'

services:
  # Laravel Application
  app:
    build: .
    container_name: malak_outlet_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./storage:/var/www/html/storage
      - ./public/images:/var/www/html/public/images
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=malak_outlet
      - DB_USERNAME=root
      - DB_PASSWORD=root_password
    depends_on:
      - db
    networks:
      - malak_network

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: malak_outlet_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: malak_outlet
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: malak_user
      MYSQL_PASSWORD: malak_password
    volumes:
      - db_data:/var/lib/mysql
      - ./database/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - malak_network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: malak_outlet_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - malak_network

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: malak_outlet_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - malak_network

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local

networks:
  malak_network:
    driver: bridge
